
name: Deploy to Developer Org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source and submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Create JWT key file
        run: |
          mkdir -p assets
          echo "${{ secrets.SF_JWT_KEY }}" > assets/server.key

      - name: Authenticate with JWT
        run: >
          sf org login jwt
          --username ${{ secrets.SF_USERNAME }}
          --client-id ${{ secrets.SF_CLIENT_ID }}
          --jwt-key-file assets/server.key
          --instance-url https://login.salesforce.com
          --alias developer

      - name: Deploy to Developer Org
        run: sf project deploy start --manifest manifest/package.xml --target-org developer

